package com.myspace.smartgym;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Exercise implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer name;
	private java.lang.Integer muscles;
	@org.kie.api.definition.type.Label(value = "Number of sets to complete")
	private int sets;
	@org.kie.api.definition.type.Label(value = "Number of reps to complete")
	private int reps;

	public Exercise() {
	}

	public java.lang.Integer getName() {
		return this.name;
	}

	public void setName(java.lang.Integer name) {
		this.name = name;
	}

	public java.lang.Integer getMuscles() {
		return this.muscles;
	}

	public void setMuscles(java.lang.Integer muscles) {
		this.muscles = muscles;
	}

	public int getSets() {
		return this.sets;
	}

	public void setSets(int sets) {
		this.sets = sets;
	}

	public int getReps() {
		return this.reps;
	}

	public void setReps(int reps) {
		this.reps = reps;
	}

	public Exercise(java.lang.Integer name, java.lang.Integer muscles,
			int sets, int reps) {
		this.name = name;
		this.muscles = muscles;
		this.sets = sets;
		this.reps = reps;
	}

}