package com.myspace.smartgym;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Exercise2 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name of the exercise")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Muscles trained")
	private java.lang.String muscles;
	@org.kie.api.definition.type.Label("Number of sets to complete")
	private int sets;
	@org.kie.api.definition.type.Label("Number of reps to complete in each set")
	private int reps;

	public Exercise2() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getMuscles() {
		return this.muscles;
	}

	public void setMuscles(java.lang.String muscles) {
		this.muscles = muscles;
	}

	public int getSets() {
		return this.sets;
	}

	public void setSets(int sets) {
		this.sets = sets;
	}

	public int getReps() {
		return this.reps;
	}

	public void setReps(int reps) {
		this.reps = reps;
	}

	public Exercise2(java.lang.String name, java.lang.String muscles, int sets,
			int reps) {
		this.name = name;
		this.muscles = muscles;
		this.sets = sets;
		this.reps = reps;
	}

}