package com.myspace.smartgym;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MealPlan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Daily calories")
	private java.lang.Integer dailyCals;
	@org.kie.api.definition.type.Label(value = "Daily protein (g)")
	private java.lang.Integer dailyProtein;
	@org.kie.api.definition.type.Label(value = "Diet recommendations")
	private java.lang.String diet;

	public MealPlan() {
	}

	public java.lang.Integer getDailyCals() {
		return this.dailyCals;
	}

	public void setDailyCals(java.lang.Integer dailyCals) {
		this.dailyCals = dailyCals;
	}

	public java.lang.Integer getDailyProtein() {
		return this.dailyProtein;
	}

	public void setDailyProtein(java.lang.Integer dailyProtein) {
		this.dailyProtein = dailyProtein;
	}

	public java.lang.String getDiet() {
		return this.diet;
	}

	public void setDiet(java.lang.String diet) {
		this.diet = diet;
	}

	public MealPlan(java.lang.Integer dailyCals,
			java.lang.Integer dailyProtein, java.lang.String diet) {
		this.dailyCals = dailyCals;
		this.dailyProtein = dailyProtein;
		this.diet = diet;
	}

}