package com.myspace.smartgym;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class RegistrationData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Sex")
	private java.lang.String sex;
	@org.kie.api.definition.type.Label("Age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label("Weight")
	private java.lang.Integer weight;
	@org.kie.api.definition.type.Label("Fitness goal")
	private java.lang.String goal;
	@org.kie.api.definition.type.Label("Credit Card number")
	private java.lang.Integer creditCard;

	@org.kie.api.definition.type.Label("Subscribe to newsletter")
	private java.lang.Boolean newsletter;

	@org.kie.api.definition.type.Label("Email address")
	private java.lang.String email;

	public RegistrationData() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getSex() {
		return this.sex;
	}

	public void setSex(java.lang.String sex) {
		this.sex = sex;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Integer getWeight() {
		return this.weight;
	}

	public void setWeight(java.lang.Integer weight) {
		this.weight = weight;
	}

	public java.lang.String getGoal() {
		return this.goal;
	}

	public void setGoal(java.lang.String goal) {
		this.goal = goal;
	}

	public java.lang.Integer getCreditCard() {
		return this.creditCard;
	}

	public void setCreditCard(java.lang.Integer creditCard) {
		this.creditCard = creditCard;
	}

	public java.lang.Boolean getNewsletter() {
		return this.newsletter;
	}

	public void setNewsletter(java.lang.Boolean newsletter) {
		this.newsletter = newsletter;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public RegistrationData(java.lang.String name, java.lang.String sex,
			java.lang.Integer age, java.lang.Integer weight,
			java.lang.String goal, java.lang.Integer creditCard,
			java.lang.Boolean newsletter, java.lang.String email) {
		this.name = name;
		this.sex = sex;
		this.age = age;
		this.weight = weight;
		this.goal = goal;
		this.creditCard = creditCard;
		this.newsletter = newsletter;
		this.email = email;
	}

}