package com.myspace.smartgym;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WorkoutPlan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Workouts")
	private String workouts;
	@org.kie.api.definition.type.Label("Cardio")
	private java.lang.String cardio;
	@org.kie.api.definition.type.Label("Workout Frequency (weekly)")
	private java.lang.Integer workoutFrequency;

	public WorkoutPlan() {
	}

	public java.lang.String getCardio() {
		return this.cardio;
	}

	public void setCardio(java.lang.String cardio) {
		this.cardio = cardio;
	}

	public java.lang.Integer getWorkoutFrequency() {
		return this.workoutFrequency;
	}

	public void setWorkoutFrequency(java.lang.Integer workoutFrequency) {
		this.workoutFrequency = workoutFrequency;
	}

	public java.lang.String getWorkouts() {
		return this.workouts;
	}

	public void setWorkouts(java.lang.String workouts) {
		this.workouts = workouts;
	}

	public WorkoutPlan(java.lang.String workouts, java.lang.String cardio,
			java.lang.Integer workoutFrequency) {
		this.workouts = workouts;
		this.cardio = cardio;
		this.workoutFrequency = workoutFrequency;
	}

}